"""lut_map.py - which colour-grading LUT each event / weather uses (read-only, from YOUR install).

  python scripts/lut_map.py            markdown tables to stdout
  python scripts/lut_map.py --md <f>   ... into a file (docs/lut-map.md is generated with this)

How the game picks a grade: every event names a weather timeline (eventdata `TimelineFileName`,
arcade: arcadeweatherdata `TimelineFilePath`, relative to data:metagame/eventTimelines/). A
timeline is a text file of keyframed streams; `Stream ColourGrading0` (also 1, 2) lists
`progress : <LUT name>` keys = data:textures/render/luts/<LUT name>.gtx, blended over the race.
"""
import collections
import json
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import d5mod  # noqa: E402
from d5ml import fnv1a64  # noqa: E402
from d5x import GAME_DAT, Index  # noqa: E402

TL = "data:metagame/eventTimelines/"
LUTS = "data:textures/render/luts/"


def load(idx, path):
    return json.loads(idx.read(idx.find(path)).rstrip(b"\0"))["objectInstances"]


def grading(text):
    """{'ColourGrading0': [(0.0, 'DIRT5_Cold_Clear_Evening'), (0.4, 'DIRT5_Cold_Clear_Day')], ...}"""
    text = re.sub(r"#.*", "", text)
    out = {}
    for name, body in re.findall(r"Stream (ColourGrading\d)\s*\{([^}]*)\}", text):
        keys = [line.split(":", 1) for line in body.strip().splitlines() if ":" in line]
        out[name] = [(float(k), v.strip()) for k, v in keys]
    return out


def build():
    orig = os.path.join(GAME_DAT, "index", "dat.ndx.d5x-orig")
    idx = Index(ndx_path=orig) if os.path.exists(orig) else Index()
    files = list(idx.files())
    luts = {os.path.basename(e["path"])[:-4].lower(): os.path.basename(e["path"])[:-4]
            for e in files if e["path"].startswith(LUTS) and e["path"].endswith(".gtx")}
    timelines = {e["path"][len(TL):].lower(): grading(idx.read(e).decode("utf-8", "replace"))
                 for e in files if e["path"].startswith(TL) and e["path"].endswith(".txt")}
    raw = idx.read(idx.find("data:localisation/pc/eng.loc"))
    eng = {struct.unpack_from("<Q", raw, o - 12)[0]: raw[o:o + n].decode("utf-8", "replace") for o, n in d5mod._loc_entries(raw)}
    tracks = {}
    for t in load(idx, "data:event/trackdata/trackdata.json"):
        loc = next((next(iter(x.values()))["Name"] for x in t.get("DataTagList", [])
                    if next(iter(x.values())).get("TagType") == "Location"), "?")
        tracks[t["Guid"]] = (loc, eng.get(fnv1a64(t.get("Localisation1", "")), t["Name"]).strip())
    events = []
    for ev in load(idx, "data:event/eventdata/eventdata.json"):
        tl = (ev.get("TimelineFileName") or "").replace("\\", "/")
        loc, track = tracks.get(ev.get("TrackGuid"), ("?", "?"))
        events.append((ev["Name"], loc, track, tl, timelines.get(tl.lower())))
    arcade = [(w["Name"], w["TimelineFilePath"], timelines.get(w["TimelineFilePath"].lower()))
              for w in load(idx, "data:event/arcadeweatherdata/arcadeweatherdata.json")]
    return luts, timelines, events, arcade


def names(g):
    return [lut for stream in sorted(g or {}) for _, lut in g[stream]]


def fmt(g):
    if not g:
        return "(no ColourGrading stream - the level default)"
    return "; ".join(" → ".join(f"{lut}" + (f" @{k:g}" if k else "") for k, lut in g[s]) for s in sorted(g))


def markdown():
    luts, timelines, events, arcade = build()
    out = ["# Colour-grading LUTs: which event uses which", "",
           "Generated by `python scripts/lut_map.py --md docs/lut-map.md` from the game data (read-only). "
           "LUT files: `data:textures/render/luts/<name>.gtx` (32 × 32 × 32, R11G11B10 float). "
           "`@0.4` = the key starts at 40 % race progress; several keys blend over the race.", "",
           "## Arcade / Free Play weather (arcadeweatherdata)", "", "| weather | timeline | LUT |", "|---|---|---|"]
    out += [f"| {n} | `{tl}` | {fmt(g)} |" for n, tl, g in arcade]
    out += ["", "**Verified in-game 2026-09-26:** tinting `DIRT5_Base_Overcast_Day` magenta, `DIRT5_Base_Clear_Day` green and "
            "`DIRT5_Cold_Clear_Day` blue turned the default Free Play race (Rio Seafront, weather *Dynamic*) magenta — as the "
            "table says. The menus use another grade and stayed normal.", "",
            "![tint probe](lut-probe.jpg)"]
    out += ["", "The arcade `Arcade_*` timelines (season variants) use:", "", "| timeline | LUT |", "|---|---|"]
    out += [f"| `{k}` | {fmt(g)} |" for k, g in sorted(timelines.items()) if k.startswith("arcade/")]
    per_loc = collections.defaultdict(collections.Counter)
    for _, loc, _, _, g in events:
        for lut in set(names(g)) or {"(level default)"}:
            per_loc[loc][lut] += 1
    out += ["", "## Career + service-pack events by location", "",
            f"{len(events)} events (eventdata `TimelineFileName`). Count = events whose timeline uses the LUT.", "",
            "| location | LUTs (events) |", "|---|---|"]
    out += [f"| {loc} | " + ", ".join(f"`{lut}` ({n})" for lut, n in c.most_common()) + " |" for loc, c in sorted(per_loc.items())]
    used = collections.Counter(lut for g in timelines.values() for lut in set(names(g)))
    missing = sorted(lut for lut in used if lut.lower() not in luts)
    unused = sorted(v for k, v in luts.items() if k not in {u.lower() for u in used})
    out += ["", "## Loose ends", "",
            "- **Named but no such LUT file:** " + (", ".join(f"`{m}` ({', '.join(sorted(k for k, g in timelines.items() if m in names(g)))})" for m in missing) or "none"),
            "- **LUT files no timeline uses:** the photo-mode filters `pm_*` (picked in photo mode), `track_*` (older per-track "
            "grades; a level can name one in its `locationdata/misc.objects`, e.g. Cathedral Beach → `track_ss`), and leftovers: "
            + ", ".join(f"`{u}`" for u in unused if not u.startswith("pm_")), ""]
    return "\n".join(out)


def main(argv):
    text = markdown()
    if "--md" in argv:
        with open(argv[argv.index("--md") + 1], "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"written {argv[argv.index('--md') + 1]}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
